// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fatssalzlbpjilxpfuhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdHNzYWx6bGJwamlseHBmdWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDM0OTUsImV4cCI6MjA3MDQ3OTQ5NX0.eO4CwmtALYv1Nf9dhrMlucqnFtwyKxfC53dnjQ6_wyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});